### PR TITLE
Fixed ordered list in README.md

### PR DESCRIPTION
**Pull request by chapay**

### CODE REVIEW

**Comment by Alaneor** [comment]
But but... you don't need to indent the code blocks if you use the ``` syntax... ?

**Comment by chapay** [comment]
If you want your numeration to be consistent then you have to:

http://daringfireball.net/projects/markdown/syntax#list

> List items may consist of multiple paragraphs. Each subsequent paragraph in a list item must be indented by either 4 spaces or one tab.

**Comment by chapay** [comment]
Also you can look at this cheatsheet:
https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#lists

**Comment by Alaneor** [comment]
Thanks! :)

**Pull request merged**
